### PR TITLE
Use new registry format, miscellaneous maintenance task improvements

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
The `version` field was added as part of #6 in this commit https://github.com/open-contracting/standard_extension_template/pull/6/commits/76661c167c7d3dfd82fe090450ec885b0d028ec1. However, I can find no public discussion as to the plans for the `version` field, which is unused.

To avoid the slight overhead of requiring extension authors to iterate a version field (which isn't presently needed by any systems that interact with extensions), I'm removing it in this PR.

**Comment by timgdavies** [comment]
There's a lot of other stuff going on in this PR distinct from the `version` change. Is it possible to split this out into separate PR? 

To check: in the new set-up, what mechanism would an interface (e.g. CoVE) use to report on the version of an extension that is in use? I'm assuming it could pick this up from the GitHub URL in the case of a particular release, but that if we're trying to be repository-host agnostic this might not always be possible?

**Comment by jpmckinney** [comment]
I'll separate the version change into its own PR - but as it is not used anywhere, I don't see much ground for keeping it.

I submitted this to CoVE:

```json
{
    "extensions":["https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1.3/extension.json","https://raw.githubusercontent.com/open-contracting/ocds_additionalContactPoints_extension/master/extension.json"],
    "releases":[],
    "version": "1.1"
}
```

It displays the names of the extensions, and the links are to the release schema, which it calculates by replacing `extension.json` with `release-schema.json`. I think URLs are sufficient to identify the extension being used. URLs are long as identifiers, but not otherwise problematic in my mind.

**Comment by timgdavies** [comment]
>  but as it is not used anywhere, I don't see much ground for keeping it.

Please consider that things may have resulted from conversations about planned features - that have not yet been implemented. 

Whilst I accept that these are not always perfectly tracked in tickets, and that sometimes things have been superseded and can be removed - features generally are not there arbitrarily. 

> It displays the names of the extensions, and the links are to the release schema

We've had discussions in the past with the team about how it would be more user friendly for these links to go to documentation, as opposed to schema. That's something I'm hoping with the new extension registry front-end will be easier to do. 

My concern was to check that that the URL (e.g.`https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1.3/extension.json`) as an identifier for an extension should always give us (in future) enough information to link the user to the correct version of extension documentation. I can see that this is possible with GitHub URLs. 

I don't know other Git platforms so well, but a quick check with a random BitBucket repo, suggests the raw URLs don't include readable branch/release names (e.g. https://bitbucket.org/atlassian/agent-charlie/src/3aa86463ed534b14d2deaaf8e9cd7815de811046/README.md?at=eventrewrite&fileviewer=file-view-default / https://bitbucket.org/atlassian/agent-charlie/raw/3aa86463ed534b14d2deaaf8e9cd7815de811046/README.md) 

This may not be a major issue - but I want to be sure we're not missing something by making ourselves dependent on Git URL structures.

**Comment by jpmckinney** [comment]
You can replace `3aa86463ed534b14d2deaaf8e9cd7815de811046` with `master` in the BitBucket URL (GitHub also has URLs for both specific commit references and branch name references). If that Bitbucket repo had tags, it'd be possible to construct a URL for a specific tag, as with GitHub. In any case, I don't believe the registry is dependent on Git URL structures.

To link to documentation, we currently rely on `documentationUrl` in `extension.json` - so we don't need to calculate the documentation URL based on the extension's base URL.

**Comment by jpmckinney** [comment]
I moved the version change to #98. I'll merge this PR as the other changes only affect the tasks in this repo, which don't affect or imply anything about other systems.

**Pull request merged**
