### PR TITLE
Remove unused "version" field from extension-schema.json

### PR DESCRIPTION
**Pull request by jpmckinney**
See earlier discussion in #97

### CODE REVIEW

**Comment by timgdavies** [comment]
Unless there is a rush to remove this, please don't merge until I've had time to fully review updates to extension handling.

**Comment by jpmckinney** [comment]
Sure - though there have been no changes to extensions, only to the registry. All significant changes to extensions would occur in the extension template. This repo is just centralized but non-authoritative testing.

**Comment by jpmckinney** [comment]
If you're thinking of looking at everything, I prepared this reference page to show the inter-dependencies https://github.com/open-contracting/standard-maintenance-scripts/blob/master/schema/README.md

**Comment by jpmckinney** [comment]
@timgdavies Do you still plan to fully review updates to extension handling before discussing this PR, and if so, when do you expect to be able to comment on this PR?

We can always re-add a `version` field once we've decided and are ready to implement one. I don't see a downside to removing it, but I see a downside to keeping it (confusion, miscommunication, etc.).

**Pull request merged**
